WEBCHILD_NAMESPACE = 'webchild'
WEBCHILD_MEMEBEROF_DATASOURCE_ID = 'webchild_member_of'
WEBCHILD_PHYSICAL_DATASOURCE_ID = 'webchild_physical_of'
WEBCHILD_SUBSTANCEOF_DATASOURCE_ID = 'webchild_substance_of'



